version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard-jobs-fixed-behat.yml

env:
  global:
    - COMPOSER_ROOT_VERSION=4.x-dev
    - SS_BASE_URL="http://localhost:8080/"
    - SS_ENVIRONMENT_TYPE="dev"
    - RECIPE_CMS_VERSION=4.x-dev

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: DB=PGSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.3
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.3
      env: DB=MYSQL PDO=1 PHPUNIT_COVERAGE_TEST=1
    - php: 7.4
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.3
      env: DB=MYSQL BEHAT_TEST=1
      # TODO https://github.com/silverstripe/silverstripe-asset-admin/issues/1163
      allow_failures: true
    - php: 7.3
      env: DB=MYSQL ASSETADMIN_TEST=1
  # TODO https://github.com/silverstripe/silverstripe-asset-admin/issues/1163
  allow_failures:
    - php: 7.3
      env: DB=MYSQL BEHAT_TEST=1

before_script:
  # separately create artifacts directory for asset-admin behat test
  - if [[ $BEHAT_TEST ]]; then mkdir ./vendor/silverstripe/asset-admin/artifacts; fi

after_failure:
  # upload artifacts from asset-admin behat test
  - if [[ $BEHAT_TEST ]]; then php ./vendor/silverstripe/framework/tests/behat/travis-upload-artifacts.php --if-env BEHAT_TEST,ARTIFACTS_BUCKET,ARTIFACTS_KEY,ARTIFACTS_SECRET --target-path $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --artifacts-base-url https://s3.amazonaws.com/$ARTIFACTS_BUCKET/ --artifacts-path ./vendor/silverstripe/asset-admin/artifacts/; fi

